/**
 * Route configuration for calculator slugs across languages
 *
 * This file maps each calculator ID to its URL slug in each language.
 * The slug is the final part of the URL path.
 *
 * Example:
 * - Calculator ID: 'bmi'
 * - Spanish URL: /calculadoras/imc/ (slug: 'imc')
 * - English URL: /en/calculators/bmi/ (slug: 'bmi')
 * - German URL: /de/rechner/bmi/ (slug: 'bmi')
 */

import type { CalculatorId } from './calculators';
import type { Locale } from './languages';

export type RouteMap = Record<Locale, Record<CalculatorId, string>>;

/**
 * Calculator slug mappings for each language
 * Format: { locale: { calculatorId: 'url-slug' } }
 */
export const routes: RouteMap = {
  es: {
    'age': 'edad',
    'army-body-fat': 'grasa-corporal-ejercito',
    'bac': 'alcoholemia',
    'bmi': 'imc',
    'bmr': 'tmb',
    'blood-type': 'tipo-sangre',
    'body-fat': 'grasa-corporal',
    'body-frame': 'complexion',
    'body-type': 'tipo-cuerpo',
    'bsa': 'superficie-corporal',
    'calorie': 'calorias',
    'calories-burned': 'calorias-quemadas',
    'carbohydrate': 'carbohidratos',
    'date': 'fecha',
    'due-date': 'fecha-parto',
    'fat-intake': 'consumo-grasas',
    'gfr': 'tasa-filtracion-glomerular',
    'healthy-weight': 'peso-saludable',
    'heart-rate': 'frecuencia-cardiaca',
    'ideal-weight': 'peso-ideal',
    'lean-body-mass': 'masa-corporal-magra',
    'macro': 'macros',
    'one-rep-max': '1rm',
    'ovulation': 'ovulacion',
    'pace': 'ritmo',
    'percentage': 'porcentaje',
    'period': 'periodo',
    'pregnancy': 'embarazo',
    'pregnancy-conception': 'concepcion-embarazo',
    'pregnancy-weight-gain': 'aumento-peso-embarazo',
    'protein': 'proteinas',
    'sleep': 'sueno',
    'tdee': 'gasto-energetico-diario',
    'tip': 'propina',
    'waist-hip': 'cintura-cadera',
    'weight-watchers': 'weight-watchers'
  },
  en: {
    'age': 'age',
    'army-body-fat': 'army-body-fat',
    'bac': 'bac',
    'bmi': 'bmi',
    'bmr': 'bmr',
    'blood-type': 'blood-type',
    'body-fat': 'body-fat',
    'body-frame': 'body-frame',
    'body-type': 'body-type',
    'bsa': 'bsa',
    'calorie': 'calorie',
    'calories-burned': 'calories-burned',
    'carbohydrate': 'carbohydrate',
    'date': 'date',
    'due-date': 'due-date',
    'fat-intake': 'fat-intake',
    'gfr': 'gfr',
    'healthy-weight': 'healthy-weight',
    'heart-rate': 'heart-rate',
    'ideal-weight': 'ideal-weight',
    'lean-body-mass': 'lean-body-mass',
    'macro': 'macro',
    'one-rep-max': 'one-rep-max',
    'ovulation': 'ovulation',
    'pace': 'pace',
    'percentage': 'percentage',
    'period': 'period',
    'pregnancy': 'pregnancy',
    'pregnancy-conception': 'pregnancy-conception',
    'pregnancy-weight-gain': 'pregnancy-weight-gain',
    'protein': 'protein',
    'sleep': 'sleep',
    'tdee': 'tdee',
    'tip': 'tip',
    'waist-hip': 'waist-hip',
    'weight-watchers': 'weight-watchers'
  },
  pt: {
    'age': 'idade',
    'army-body-fat': 'gordura-corporal-exercito',
    'bac': 'alcoolemia',
    'bmi': 'imc',
    'bmr': 'tmb',
    'blood-type': 'tipo-sanguineo',
    'body-fat': 'gordura-corporal',
    'body-frame': 'estrutura-corporal',
    'body-type': 'tipo-corpo',
    'bsa': 'superficie-corporal',
    'calorie': 'calorias',
    'calories-burned': 'calorias-queimadas',
    'carbohydrate': 'carboidratos',
    'date': 'data',
    'due-date': 'data-parto',
    'fat-intake': 'consumo-gorduras',
    'gfr': 'taxa-filtracao-glomerular',
    'healthy-weight': 'peso-saudavel',
    'heart-rate': 'frequencia-cardiaca',
    'ideal-weight': 'peso-ideal',
    'lean-body-mass': 'massa-corporal-magra',
    'macro': 'macros',
    'one-rep-max': '1rm',
    'ovulation': 'ovulacao',
    'pace': 'ritmo',
    'percentage': 'porcentagem',
    'period': 'periodo',
    'pregnancy': 'gravidez',
    'pregnancy-conception': 'concepcao-gravidez',
    'pregnancy-weight-gain': 'aumento-peso-gravidez',
    'protein': 'proteinas',
    'sleep': 'sono',
    'tdee': 'gasto-energetico-diario',
    'tip': 'gorjeta',
    'waist-hip': 'cintura-quadril',
    'weight-watchers': 'weight-watchers'
  },
  fr: {
    'age': 'age',
    'army-body-fat': 'graisse-corporelle-armee',
    'bac': 'alcoolemie',
    'bmi': 'imc',
    'bmr': 'mb',
    'blood-type': 'groupe-sanguin',
    'body-fat': 'graisse-corporelle',
    'body-frame': 'morphologie',
    'body-type': 'type-corps',
    'bsa': 'surface-corporelle',
    'calorie': 'calories',
    'calories-burned': 'calories-brulees',
    'carbohydrate': 'glucides',
    'date': 'date',
    'due-date': 'date-accouchement',
    'fat-intake': 'apport-lipides',
    'gfr': 'debit-filtration-glomerulaire',
    'healthy-weight': 'poids-sante',
    'heart-rate': 'frequence-cardiaque',
    'ideal-weight': 'poids-ideal',
    'lean-body-mass': 'masse-maigre',
    'macro': 'macros',
    'one-rep-max': '1rm',
    'ovulation': 'ovulation',
    'pace': 'allure',
    'percentage': 'pourcentage',
    'period': 'regles',
    'pregnancy': 'grossesse',
    'pregnancy-conception': 'conception-grossesse',
    'pregnancy-weight-gain': 'prise-poids-grossesse',
    'protein': 'proteines',
    'sleep': 'sommeil',
    'tdee': 'depense-energetique-quotidienne',
    'tip': 'pourboire',
    'waist-hip': 'taille-hanches',
    'weight-watchers': 'weight-watchers'
  },
  hi: {
    'age': 'age',
    'army-body-fat': 'army-body-fat',
    'bac': 'bac',
    'bmi': 'bmi',
    'bmr': 'bmr',
    'blood-type': 'blood-type',
    'body-fat': 'body-fat',
    'body-frame': 'body-frame',
    'body-type': 'body-type',
    'bsa': 'bsa',
    'calorie': 'calorie',
    'calories-burned': 'calories-burned',
    'carbohydrate': 'carbohydrate',
    'date': 'date',
    'due-date': 'due-date',
    'fat-intake': 'fat-intake',
    'gfr': 'gfr',
    'healthy-weight': 'healthy-weight',
    'heart-rate': 'heart-rate',
    'ideal-weight': 'ideal-weight',
    'lean-body-mass': 'lean-body-mass',
    'macro': 'macro',
    'one-rep-max': 'one-rep-max',
    'ovulation': 'ovulation',
    'pace': 'pace',
    'percentage': 'percentage',
    'period': 'period',
    'pregnancy': 'pregnancy',
    'pregnancy-conception': 'pregnancy-conception',
    'pregnancy-weight-gain': 'pregnancy-weight-gain',
    'protein': 'protein',
    'sleep': 'sleep',
    'tdee': 'tdee',
    'tip': 'tip',
    'waist-hip': 'waist-hip',
    'weight-watchers': 'weight-watchers'
  },
  de: {
    'age': 'alter',
    'army-body-fat': 'army-body-fat',
    'bac': 'bak',
    'bmi': 'bmi',
    'bmr': 'bmr',
    'blood-type': 'blood-type',
    'body-fat': 'body-fat',
    'body-frame': 'body-frame',
    'body-type': 'body-type',
    'bsa': 'bsa',
    'calorie': 'kalorien',
    'calories-burned': 'verbrannte-kalorien',
    'carbohydrate': 'kohlenhydrate',
    'date': 'datum',
    'due-date': 'geburtstermin',
    'fat-intake': 'fettaufnahme',
    'gfr': 'gfr',
    'healthy-weight': 'gesundes-gewicht',
    'heart-rate': 'herzfrequenz',
    'ideal-weight': 'idealgewicht',
    'lean-body-mass': 'magermasse',
    'macro': 'makros',
    'one-rep-max': '1rm',
    'ovulation': 'eisprung',
    'pace': 'tempo',
    'percentage': 'prozentsatz',
    'period': 'periode',
    'pregnancy': 'schwangerschaft',
    'pregnancy-conception': 'empfangnis-schwangerschaft',
    'pregnancy-weight-gain': 'gewichtszunahme-schwangerschaft',
    'protein': 'protein',
    'sleep': 'schlaf',
    'tdee': 'gesamtumsatz',
    'tip': 'trinkgeld',
    'waist-hip': 'taille-hufte',
    'weight-watchers': 'weight-watchers'
  },
  it: {
    'age': 'eta',
    'army-body-fat': 'grasso-corporeo-esercito',
    'bac': 'tasso-alcolemico',
    'bmi': 'imc',
    'bmr': 'mb',
    'blood-type': 'gruppo-sanguigno',
    'body-fat': 'grasso-corporeo',
    'body-frame': 'corporatura',
    'body-type': 'tipo-corpo',
    'bsa': 'superficie-corporea',
    'calorie': 'calorie',
    'calories-burned': 'calorie-bruciate',
    'carbohydrate': 'carboidrati',
    'date': 'data',
    'due-date': 'data-parto',
    'fat-intake': 'assunzione-grassi',
    'gfr': 'velocita-filtrazione-glomerulare',
    'healthy-weight': 'peso-salutare',
    'heart-rate': 'frequenza-cardiaca',
    'ideal-weight': 'peso-ideale',
    'lean-body-mass': 'massa-magra',
    'macro': 'macro',
    'one-rep-max': '1rm',
    'ovulation': 'ovulazione',
    'pace': 'ritmo',
    'percentage': 'percentuale',
    'period': 'periodo',
    'pregnancy': 'gravidanza',
    'pregnancy-conception': 'concepimento-gravidanza',
    'pregnancy-weight-gain': 'aumento-peso-gravidanza',
    'protein': 'proteine',
    'sleep': 'sonno',
    'tdee': 'dispendio-energetico-totale',
    'tip': 'mancia',
    'waist-hip': 'vita-fianchi',
    'weight-watchers': 'weight-watchers'
  },
  pl: {
    'age': 'wiek',
    'army-body-fat': 'tkanka-tluszczowa-wojsko',
    'bac': 'alkohol-we-krwi',
    'bmi': 'bmi',
    'bmr': 'ppm',
    'blood-type': 'grupa-krwi',
    'body-fat': 'tkanka-tluszczowa',
    'body-frame': 'budowa-ciala',
    'body-type': 'typ-sylwetki',
    'bsa': 'powierzchnia-ciala',
    'calorie': 'kalorie',
    'calories-burned': 'spalone-kalorie',
    'carbohydrate': 'weglowodany',
    'date': 'data',
    'due-date': 'termin-porodu',
    'fat-intake': 'spozycie-tluszczow',
    'gfr': 'przesaczanie-klebuszkowe',
    'healthy-weight': 'zdrowa-waga',
    'heart-rate': 'tetno',
    'ideal-weight': 'idealna-waga',
    'lean-body-mass': 'beztluszczowa-masa-ciala',
    'macro': 'makroskadniki',
    'one-rep-max': '1rm',
    'ovulation': 'owulacja',
    'pace': 'tempo',
    'percentage': 'procent',
    'period': 'okres',
    'pregnancy': 'ciaza',
    'pregnancy-conception': 'poczecie-ciaza',
    'pregnancy-weight-gain': 'przyrost-masy-ciaza',
    'protein': 'bialko',
    'sleep': 'sen',
    'tdee': 'calkowite-wydatki-energetyczne',
    'tip': 'napiwek',
    'waist-hip': 'talia-biodra',
    'weight-watchers': 'weight-watchers'
  },
  nl: {
    'age': 'leeftijd',
    'army-body-fat': 'lichaamsvet-leger',
    'bac': 'bac',
    'bmi': 'bmi',
    'bmr': 'bmr',
    'blood-type': 'bloedgroep',
    'body-fat': 'lichaamsvet',
    'body-frame': 'lichaamsbouw',
    'body-type': 'lichaamstype',
    'bsa': 'lichaamsoppervlak',
    'calorie': 'calorieen',
    'calories-burned': 'verbrande-calorieen',
    'carbohydrate': 'koolhydraten',
    'date': 'datum',
    'due-date': 'uitgerekende-datum',
    'fat-intake': 'vetinname',
    'gfr': 'gfr',
    'healthy-weight': 'gezond-gewicht',
    'heart-rate': 'hartslag',
    'ideal-weight': 'ideaal-gewicht',
    'lean-body-mass': 'vetvrije-massa',
    'macro': 'macros',
    'one-rep-max': '1rm',
    'ovulation': 'eisprong',
    'pace': 'tempo',
    'percentage': 'percentage',
    'period': 'periode',
    'pregnancy': 'zwangerschap',
    'pregnancy-conception': 'conceptie-zwangerschap',
    'pregnancy-weight-gain': 'gewichtstoename-zwangerschap',
    'protein': 'proteinen',
    'sleep': 'slaap',
    'tdee': 'totaal-dagelijks-energieverbruik',
    'tip': 'fooi',
    'waist-hip': 'taille-heup',
    'weight-watchers': 'weight-watchers'
  },
  tr: {
    'age': 'yas',
    'army-body-fat': 'ordu-vucut-yag',
    'bac': 'kan-alkol',
    'bmi': 'vki',
    'bmr': 'bmh',
    'blood-type': 'kan-grubu',
    'body-fat': 'vucut-yag',
    'body-frame': 'vucut-yapilanmasi',
    'body-type': 'vucut-tipi',
    'bsa': 'vucut-yuzey-alani',
    'calorie': 'kalori',
    'calories-burned': 'yakilan-kalori',
    'carbohydrate': 'karbonhidrat',
    'date': 'tarih',
    'due-date': 'dogum-tarihi',
    'fat-intake': 'yag-tuketimi',
    'gfr': 'glomerular-filtrasyon-hizi',
    'healthy-weight': 'saglikli-kilo',
    'heart-rate': 'kalp-hizi',
    'ideal-weight': 'ideal-kilo',
    'lean-body-mass': 'yagsiz-vucut-kutle',
    'macro': 'makrolar',
    'one-rep-max': '1rm',
    'ovulation': 'yumurtlama',
    'pace': 'tempo',
    'percentage': 'yuzde',
    'period': 'donem',
    'pregnancy': 'hamilelik',
    'pregnancy-conception': 'gebelik-donemi',
    'pregnancy-weight-gain': 'hamilelik-kilo-alimi',
    'protein': 'protein',
    'sleep': 'uyku',
    'tdee': 'gunluk-enerji-harcamasi',
    'tip': 'bahsis',
    'waist-hip': 'bel-kalca',
    'weight-watchers': 'weight-watchers'
  },
  sv: {
    'age': 'alder',
    'army-body-fat': 'kroppsfett-militaren',
    'bac': 'promille',
    'bmi': 'bmi',
    'bmr': 'bmr',
    'blood-type': 'blodgrupp',
    'body-fat': 'kroppsfett',
    'body-frame': 'kroppsbyggnad',
    'body-type': 'kroppstyp',
    'bsa': 'kroppsyta',
    'calorie': 'kalorier',
    'calories-burned': 'branda-kalorier',
    'carbohydrate': 'kolhydrater',
    'date': 'datum',
    'due-date': 'beraknad-forlossning',
    'fat-intake': 'fettintag',
    'gfr': 'gfr',
    'healthy-weight': 'halsosamvikt',
    'heart-rate': 'hjartfrekvens',
    'ideal-weight': 'idealvikt',
    'lean-body-mass': 'fettfri-massa',
    'macro': 'makron',
    'one-rep-max': '1rm',
    'ovulation': 'agglosning',
    'pace': 'tempo',
    'percentage': 'procent',
    'period': 'period',
    'pregnancy': 'graviditet',
    'pregnancy-conception': 'befruktning-graviditet',
    'pregnancy-weight-gain': 'viktuppgang-graviditet',
    'protein': 'protein',
    'sleep': 'somn',
    'tdee': 'total-daglig-energiforbrukning',
    'tip': 'dricks',
    'waist-hip': 'midja-hoft',
    'weight-watchers': 'weight-watchers'
  },
  ru: {
    'age': 'vozrast',
    'army-body-fat': 'zhir-tela-armiya',
    'bac': 'uroven-alkogolya',
    'bmi': 'imt',
    'bmr': 'obm',
    'blood-type': 'gruppa-krovi',
    'body-fat': 'zhir-tela',
    'body-frame': 'teloslozheniye',
    'body-type': 'tip-tela',
    'bsa': 'poverkhnost-tela',
    'calorie': 'kalorii',
    'calories-burned': 'sozhzhennye-kalorii',
    'carbohydrate': 'uglevody',
    'date': 'data',
    'due-date': 'data-rodov',
    'fat-intake': 'potrebleniye-zhirov',
    'gfr': 'skorost-klubochkovoy-filtratsii',
    'healthy-weight': 'zdorovyy-ves',
    'heart-rate': 'puls',
    'ideal-weight': 'idealnyy-ves',
    'lean-body-mass': 'myshechnaya-massa',
    'macro': 'makronutrienty',
    'one-rep-max': '1rm',
    'ovulation': 'ovulyatsiya',
    'pace': 'temp',
    'percentage': 'protsent',
    'period': 'period',
    'pregnancy': 'beremennost',
    'pregnancy-conception': 'zachatiye-beremennost',
    'pregnancy-weight-gain': 'nabor-vesa-beremennost',
    'protein': 'belok',
    'sleep': 'son',
    'tdee': 'obshchiy-raskhod-energii',
    'tip': 'chaevyye',
    'waist-hip': 'taliya-bedra',
    'weight-watchers': 'weight-watchers'
  }
};

/**
 * Get the slug for a calculator in a specific language
 */
export function getSlug(calculatorId: CalculatorId, locale: Locale): string {
  return routes[locale][calculatorId];
}

/**
 * Find calculator ID from a slug in a specific language
 */
export function getCalculatorIdFromSlug(slug: string, locale: Locale): CalculatorId | null {
  const entry = Object.entries(routes[locale]).find(([_, routeSlug]) => routeSlug === slug);
  return entry ? (entry[0] as CalculatorId) : null;
}
